# Generated by Django 4.2.8 on 2026-03-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='employee_id',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='employee_id',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='joining_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='qualification',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='specialization',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
