# Generated by Django 4.2.8 on 2026-03-13 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
        ('academic', '0002_semesterenrollment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='semesterenrollment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='teachersubjectassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='saas.organization'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='saas.organization'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='saas.organization'),
        ),
        migrations.AddField(
            model_name='class',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='saas.organization'),
        ),
        migrations.AddField(
            model_name='course',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='saas.organization'),
        ),
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='saas.organization'),
        ),
        migrations.AddField(
            model_name='semesterenrollment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester_enrollments', to='saas.organization'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='saas.organization'),
        ),
        migrations.AddField(
            model_name='subject',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='saas.organization'),
        ),
        migrations.AddField(
            model_name='teachersubjectassignment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_subject_assignments', to='saas.organization'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='year',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(fields=('organization', 'year'), name='unique_academic_year_per_org'),
        ),
        migrations.AddConstraint(
            model_name='assignmentsubmission',
            constraint=models.UniqueConstraint(fields=('organization', 'assignment', 'student'), name='unique_assignment_submission_per_org'),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('organization', 'course', 'year', 'semester', 'section', 'academic_year'), name='unique_class_per_org'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_course_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_department_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_department_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='semesterenrollment',
            constraint=models.UniqueConstraint(fields=('organization', 'student', 'course', 'year', 'semester', 'academic_year'), name='unique_semester_enrollment_per_org'),
        ),
        migrations.AddConstraint(
            model_name='studentenrollment',
            constraint=models.UniqueConstraint(fields=('organization', 'student', 'class_enrolled'), name='unique_student_class_enrollment_per_org'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('organization', 'code', 'course'), name='unique_subject_code_course_per_org'),
        ),
        migrations.AddConstraint(
            model_name='teachersubjectassignment',
            constraint=models.UniqueConstraint(fields=('organization', 'teacher', 'subject', 'class_assigned', 'academic_year'), name='unique_teacher_subject_assignment_per_org'),
        ),
    ]
