# Generated by Django 4.2.8 on 2026-03-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0002_invoice_organization_phone_paymentmethod_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentevent',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
