"""
Django settings for student_management_system project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&%hzjkd&8o=l13023hr)fc^h*0%h%ar*1b7rp-d(09e2u83qar'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    #'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bootstrap5',
    'saas',
    'accounts',
    'academic',
    'attendance',
    'examination',
    'notifications',
    'fees.apps.FeesConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'saas.middleware.TenantMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'attendance.middleware.EnhancedTeacherAttendanceMiddleware',  # Enhanced automatic teacher attendance tracking
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Tenant-aware authentication backend for multi-tenant system
AUTHENTICATION_BACKENDS = [
    'accounts.auth_backend.TenantAuthBackend',
]

ROOT_URLCONF = 'student_management_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'saas.context_processors.tenant_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'student_management_system.wsgi.application'


# ============================================================================
# Multi-Tenant Database Configuration
# ============================================================================
# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',  # System/shared database for SaaS infrastructure
    }
}

# Database router for multi-tenant architecture
DATABASE_ROUTERS = ['saas.db_router.TenantDatabaseRouter']

# Function to add a tenant database dynamically
def add_tenant_database(organization_id, organization_slug):
    """Add a new tenant database to the DATABASES configuration"""
    db_name = f'tenant_{organization_id}'
    
    if db_name not in DATABASES:
        # Copy default database config and just change the NAME
        default_config = DATABASES['default'].copy()
        default_config['NAME'] = BASE_DIR / 'tenant_databases' / f'db_{organization_slug}.sqlite3'
        DATABASES[db_name] = default_config
    
    return db_name


# Auto-load all existing tenant databases on startup
def load_tenant_databases():
    """
    Automatically load all existing tenant database files from the file system.
    This scans the tenant_databases directory and registers any db_*.sqlite3 files.
    """
    from pathlib import Path
    
    tenant_db_dir = BASE_DIR / 'tenant_databases'
    
    if not tenant_db_dir.exists():
        return
    
    # Find all db_*.sqlite3 files
    for db_file in tenant_db_dir.glob('db_*.sqlite3'):
        # Extract slug from filename: db_<slug>.sqlite3
        slug = db_file.stem.replace('db_', '')
        
        # Infer organization ID from slug patterns
        # For "sos-herman-gmeiner-school" slug, organization ID should be 1
        # For now, just register all found databases
        import re
        
        # Try pattern matching to find organization ID
        # Most common: organization ID 1 has slug "sos-herman-gmeiner-school"
        org_id = None
        
        # Try querying Organization if it's available
        try:
            if apps.ready:
                from saas.models import Organization
                org = Organization.objects.using('default').filter(slug=slug).first()
                if org:
                    org_id = org.id
                    add_tenant_database(org.id, org.slug)
        except Exception:
            # If we can't query, try to infer from slug
            pass
        
        # If we couldn't get org_id from database, try to infer
        if not org_id:
            # For Sos Herman Gmeiner School, assume ID 1
            if 'sos-herman-gmeiner' in slug:
                add_tenant_database(1, slug)


# Load tenant databases when settings are loaded
try:
    load_tenant_databases()
except Exception as e:
    # Log but don't fail startup
    import sys
    print(f"Warning: Could not load tenant databases: {e}", file=sys.stderr)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Crispy Forms Configuration
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Static files
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Login URLs
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'accounts:dashboard'
LOGOUT_REDIRECT_URL = 'accounts:login'

# Email Configuration (for notifications)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# Custom User Model
AUTH_USER_MODEL = 'accounts.User'
# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CSRF_TRUSTED_ORIGINS = [
    "http://192.168.18.169:8000",
]

# ============================================================================
# SaaS & Subscription Configuration
# ============================================================================

# Stripe Configuration
STRIPE_PUBLIC_KEY = os.environ.get('STRIPE_PUBLIC_KEY', '')
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', '')

# Billing Settings
BILLING_SETTINGS = {
    'TRIAL_DAYS': 14,
    'INVOICE_DAYS_UNTIL_DUE': 30,
    'AUTO_BILLING_ENABLED': True,
    'INVOICE_PREFIX': 'INV',
}

# Feature Flags by Plan
FEATURE_FLAGS = {
    'free': {
        'max_students': 50,
        'max_teachers': 5,
        'max_admins': 1,
        'features': {
            'attendance_tracking': True,
            'grade_management': True,
            'fee_management': False,
            'advanced_reports': False,
            'api_access': False,
        }
    },
    'starter': {
        'max_students': 500,
        'max_teachers': 20,
        'max_admins': 3,
        'features': {
            'attendance_tracking': True,
            'grade_management': True,
            'fee_management': True,
            'advanced_reports': False,
            'api_access': False,
        }
    },
    'professional': {
        'max_students': 2000,
        'max_teachers': 100,
        'max_admins': 10,
        'features': {
            'attendance_tracking': True,
            'grade_management': True,
            'fee_management': True,
            'advanced_reports': True,
            'api_access': True,
        }
    },
    'enterprise': {
        'max_students': None,  # Unlimited
        'max_teachers': None,
        'max_admins': None,
        'features': {
            'attendance_tracking': True,
            'grade_management': True,
            'fee_management': True,
            'advanced_reports': True,
            'api_access': True,
            'custom_branding': True,
            'dedicated_support': True,
        }
    },
}

# Celery Configuration (for async billing tasks)
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

# CORS Settings (for API)
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:8000',
]
