# Generated by Django 4.2.8 on 2026-03-13 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
        ('attendance', '0005_geofencelocation_teacherschedule_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesummary',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='teacherattendance',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='teacherschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='saas.organization'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='saas.organization'),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='saas.organization'),
        ),
        migrations.AddField(
            model_name='geofencelocation',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geofence_locations', to='saas.organization'),
        ),
        migrations.AddField(
            model_name='teacheractivitylog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_activity_logs', to='saas.organization'),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_attendance_records', to='saas.organization'),
        ),
        migrations.AddField(
            model_name='teacherleave',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_leaves', to='saas.organization'),
        ),
        migrations.AddField(
            model_name='teacherschedule',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_schedules', to='saas.organization'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('organization', 'session', 'student'), name='unique_attendance_record_per_org'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(fields=('organization', 'teacher_assignment', 'date', 'start_time'), name='unique_attendance_session_per_org'),
        ),
        migrations.AddConstraint(
            model_name='attendancesummary',
            constraint=models.UniqueConstraint(fields=('organization', 'student', 'subject', 'class_enrolled', 'month', 'year'), name='unique_attendance_summary_per_org'),
        ),
        migrations.AddConstraint(
            model_name='teacherattendance',
            constraint=models.UniqueConstraint(fields=('organization', 'teacher', 'date'), name='unique_teacher_attendance_per_org'),
        ),
        migrations.AddConstraint(
            model_name='teacherschedule',
            constraint=models.UniqueConstraint(fields=('organization', 'teacher', 'subject_assignment', 'day_of_week', 'start_time'), name='unique_teacher_schedule_per_org'),
        ),
    ]
